version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting_db
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  vote-app:
    build: ./vote
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/voting_db
      - REDIS_URL=redis://redis:6379/0

  result-app:
    build: ./result
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/voting_db

  worker:
    build: ./worker
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/voting_db
      - REDIS_URL=redis://redis:6379/0

volumes:
  db_data:
